name: phpunit

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1]
        stability: [prefer-lowest, prefer-stable]
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    steps:
      - uses: actions/checkout@v3
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: xdebug
      - run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction
      - run: composer run phpunit
      # - uses: timkrase/phpunit-coverage-badge@v1.2.0
      #   with:
      #     push_badge: true
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     report: tests/results/coverage.xml
      #     coverage_badge_path: tests/coverage.svg
